#!/usr/bin/env python3
"""gen-skill-adapters.py -- generated, tracked skill-discovery adapters for non-Claude
agents (backlog v3.0-79).

Codex (and other agents following the .agents convention) discover repository skills from
`.agents/skills/<name>/SKILL.md`; this repo's canonical skill protocols live at
`.claude/skills/<name>/SKILL.md`. The historical answer was a HAND-BUILT mirror -- which
this repo's own review corpus condemned in June 2026 ("untracked mirror harnesses sit
outside every sensor's scope", wiki/REVIEW.md; "mirror ownership unclear", receipts
2026-06-11): hand copies drift silently. This generator replaces the copy with a derived
projection: one pointer adapter per installed skill, frontmatter (name + description)
copied verbatim so discovery and triggering work, body a pointer to the canonical
protocol -- never duplicated instructions (single-home rule). Adapters are TRACKED and
regenerable; /doctor's skill-adapters check runs `--check` so drift fails loud instead of
accumulating invisibly.

SKIPPED skills (SKIP_SKILLS below): cross-check and cross-check-loop are
substrate-DIRECTIONAL -- their protocol dispatches this repo's Claude->Codex verify
bridge, so a Codex session running them would produce a same-vendor "cross"-check, the
exact conflation class of backlog v3.0-76. A non-Claude session needing a second opinion
uses its own native cross-vendor tooling instead. The skip is by design, not an omission.

Usage:
  gen-skill-adapters.py [--root DIR]         regenerate .agents/skills/ (idempotent)
  gen-skill-adapters.py --check [--root DIR] exit 0 if current, 1 if regeneration would
                                             change anything (doctor consumes this)
  gen-skill-adapters.py --self-test          embedded fixtures, temp dir only
Exit: 0 ok/current | 1 drift (--check) or self-test failure | 2 usage/environment error.
"""

import argparse
import re
import shutil
import sys
import tempfile
from pathlib import Path

SKIP_SKILLS = {
    "cross-check": "substrate-directional (dispatches the Claude->Codex bridge; "
                    "same-vendor if run from Codex -- v3.0-76 class)",
    "cross-check-loop": "substrate-directional (same reason as cross-check)",
}

_FM_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_NAME_RE = re.compile(r"(?m)^name:\s*(.+?)\s*$")
_DESC_RE = re.compile(r"(?m)^description:\s*(.+?)\s*$")

ADAPTER_BODY = """\
# /%(name)s — discovery adapter

**This file is a GENERATED pointer, not the protocol.** The canonical, complete protocol
for this skill lives at:

    .claude/skills/%(name)s/SKILL.md

Read and follow that file; treat this adapter as a signpost only. The `.claude/` path is
a Claude Code layout convention, nothing more — the protocol itself is substrate-neutral
and binds any agent that runs it (see AGENTS.md, "Skills are protocols, not Claude
features").

Do not edit this file and do not add instructions here (single-home rule): it is
regenerated by `python deploy/gen-skill-adapters.py`, and /doctor's `skill-adapters`
check flags any drift between the adapters and the canonical skill set.
"""


def _parse_frontmatter(text):
    """(name, description) from a SKILL.md, or (None, None) if unparseable."""
    m = _FM_RE.match(text)
    if not m:
        return None, None
    block = m.group(1)
    name = _NAME_RE.search(block)
    desc = _DESC_RE.search(block)
    return (name.group(1) if name else None, desc.group(1) if desc else None)


def render_adapter(name, description):
    return ("---\n"
            "name: %s\n"
            "description: %s\n"
            "---\n\n" % (name, description)) + ADAPTER_BODY % {"name": name}


def desired_adapters(root):
    """{skill_name: adapter_text} for every canonical skill not skipped."""
    skills_dir = root / ".claude" / "skills"
    out = {}
    if not skills_dir.is_dir():
        return out
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        skill = skill_md.parent.name
        if skill in SKIP_SKILLS:
            continue
        name, desc = _parse_frontmatter(skill_md.read_text(encoding="utf-8",
                                                            errors="ignore"))
        if not name or not desc:
            print("WARN: %s has no parseable name/description frontmatter -- skipped "
                  "(fix the canonical skill, then re-run)" % skill_md, file=sys.stderr)
            continue
        out[skill] = render_adapter(name, desc)
    return out


def current_adapters(root):
    """{skill_name: adapter_text} for what is on disk under .agents/skills/."""
    agents_dir = root / ".agents" / "skills"
    out = {}
    if not agents_dir.is_dir():
        return out
    for adapter_md in sorted(agents_dir.glob("*/SKILL.md")):
        out[adapter_md.parent.name] = adapter_md.read_text(encoding="utf-8",
                                                            errors="ignore")
    return out


def diff(root):
    """(stale, missing, orphaned) skill-name lists. Empty everywhere == current."""
    want = desired_adapters(root)
    have = current_adapters(root)
    stale = sorted(k for k in want if k in have and have[k] != want[k])
    missing = sorted(k for k in want if k not in have)
    orphaned = sorted(k for k in have if k not in want)
    return stale, missing, orphaned


def regenerate(root):
    want = desired_adapters(root)
    agents_dir = root / ".agents" / "skills"
    _, missing, orphaned = diff(root)
    for skill, text in want.items():
        d = agents_dir / skill
        d.mkdir(parents=True, exist_ok=True)
        target = d / "SKILL.md"
        if not target.exists() or target.read_text(encoding="utf-8",
                                                    errors="ignore") != text:
            target.write_text(text, encoding="utf-8", newline="\n")
    for skill in orphaned:
        shutil.rmtree(agents_dir / skill)
    return len(want), len(missing), len(orphaned)


def self_test():
    failed = total = 0

    def check(label, cond):
        nonlocal failed, total
        total += 1
        print("  %s %s" % ("ok " if cond else "XX ", label))
        if not cond:
            failed += 1

    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        sk = root / ".claude" / "skills"
        for name, desc in (("alpha", "First test skill."),
                            ("cross-check", "Skipped by design."),
                            ("beta", "Second test skill.")):
            d = sk / name
            d.mkdir(parents=True)
            (d / "SKILL.md").write_text("---\nname: %s\ndescription: %s\n---\nbody\n"
                                         % (name, desc), encoding="utf-8")

        n, missing, orphaned = regenerate(root)
        check("generates one adapter per non-skipped skill (2, not 3)", n == 2)
        check("skip-listed skill got no adapter",
              not (root / ".agents" / "skills" / "cross-check").exists())
        check("adapter carries copied description",
              "First test skill." in (root / ".agents" / "skills" / "alpha" /
                                       "SKILL.md").read_text(encoding="utf-8"))
        s, m, o = diff(root)
        check("post-regenerate: current (no stale/missing/orphaned)",
              not s and not m and not o)

        # Drift: canonical description changes -> adapter stale until regenerated.
        (sk / "alpha" / "SKILL.md").write_text(
            "---\nname: alpha\ndescription: CHANGED.\n---\nbody\n", encoding="utf-8")
        s, m, o = diff(root)
        check("canonical edit -> adapter reported stale", s == ["alpha"])

        # Orphan: skill deleted -> adapter reported orphaned, removed on regenerate.
        shutil.rmtree(sk / "beta")
        s, m, o = diff(root)
        check("deleted skill -> adapter reported orphaned", o == ["beta"])
        regenerate(root)
        s, m, o = diff(root)
        check("regenerate heals stale + removes orphan", not s and not m and not o)

    print("gen-skill-adapters self-test: %s (%d/%d)"
          % ("FAIL" if failed else "PASS", total - failed, total))
    return 1 if failed else 0


def main(argv=None):
    ap = argparse.ArgumentParser(prog="gen-skill-adapters.py")
    ap.add_argument("--root", default=None)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return self_test()
    root = Path(args.root).resolve() if args.root else Path.cwd().resolve()
    if not (root / ".claude" / "skills").is_dir():
        print("gen-skill-adapters: no .claude/skills under %s" % root, file=sys.stderr)
        return 2
    if args.check:
        stale, missing, orphaned = diff(root)
        if stale or missing or orphaned:
            print("skill-adapters DRIFT: stale=%s missing=%s orphaned=%s"
                  % (stale, missing, orphaned))
            return 1
        print("skill-adapters current (%d adapters, %d skills skipped by design)"
              % (len(desired_adapters(root)), len(SKIP_SKILLS)))
        return 0
    n, missing, orphaned = regenerate(root)
    print("skill-adapters regenerated: %d adapter(s); %d were missing, %d orphan(s) "
          "removed; skipped by design: %s"
          % (n, missing, orphaned, ", ".join(sorted(SKIP_SKILLS))))
    return 0


if __name__ == "__main__":
    sys.exit(main())
