#!/usr/bin/env python3
"""gen-desk.py -- the desk generator (session D, v3.0-39, desk enrichment).

session-d-design-brief-2026-07-23.md Part 2 item 6: DESK.html is a STATIC PROJECTION, an
actuator-free glass -- zero JavaScript, no <script>/<form>/<button> tags anywhere in the
output, every link either `file://` or a plain relative href. Nothing on the page DOES
anything; it only shows what is already true on disk. Regenerated by the same write-side
sessions that append to the metrics history (the /standing-loop payload and the
scheduled-recipe session -- see .claude/skills/sweep/SKILL.md's amended "Scheduling"
section); a direct, manual /sweep run never calls this script either.

COMPOSED FROM four sources, each read-only and each independently tolerant of absence (an
absent source renders one honest "not available" block in its place, never a crash and
never silently skipped):
  1. SWEEP-BRIEFING.md    -- its three named sections (All clear / Needs your attention /
                              Watching), rendered VERBATIM (escaped, paragraph-wrapped;
                              content is not summarized or reworded).
  2. DECISIONS-PENDING.md -- item TITLES grouped by their source heading, with a "waiting
                              N days" age badge when `receipts/desk/inbox-first-seen.json`
                              exists AND (tolerantly) contains a recognizable entry for
                              that exact item text -- ages are a bonus, never required for
                              the item itself to render (that sidecar is deploy/
                              decision-inbox.py's file, a different builder's; this script
                              only ever reads it, and reads it defensively against shape
                              drift: any JSON that isn't the two shapes this script
                              recognizes degrades to "no ages available", not a crash).
  3. `deploy/check-deadlines.py --json` -- the register's countdowns (attention / fired /
                              watching / if-rows), run fresh at generation time.
  4. `deploy/desk-metrics.py --trends --json` -- the plain-English trend lines over
                              `receipts/desk/metrics-history.jsonl`.

Visual style is cribbed from core/onboarding/SYSTEM-MAP.html's design tokens (the same
:root CSS custom-property palette, light/dark via prefers-color-scheme + a dormant
data-theme override) so the desk reads as part of the same system -- minus SYSTEM-MAP's
tab/toggle/disclosure JS, none of which belongs on an actuator-free page.

Hermetic --self-test: renders from fixtures into a temp dir and asserts both structure
(every section present, absence handled) and the actuator-free invariant itself (zero
<script>/<form>/<button> tags, case-insensitively, anywhere in the output bytes).

Usage:
  gen-desk.py [--root PATH] [--out PATH] [--briefing PATH] [--decisions PATH]
              [--inbox-first-seen PATH] [--deploy-dir PATH] [--history PATH]
              [--register PATH] [--fork-root PATH] [--template-root PATH]
              [--today YYYY-MM-DD]
  gen-desk.py --self-test
Exit: 0 on any completed generation (report/generation primitive, never a gate) |
  nonzero only from --self-test on failure.
"""

import html as _html
import json
import os
import re
import subprocess
import sys
from datetime import date, datetime

_HERE = os.path.dirname(os.path.abspath(__file__))

# The briefing's three named sections (.claude/skills/sweep/SKILL.md "The briefing") come
# in two shapes: "**All clear:** <content on the same line>" and "**Needs your
# attention:**\n\n1. ..." (heading alone, content follows on later lines). This single
# regex handles both -- the colon is mandatory (distinguishes a real section heading from
# incidental prose starting with one of these words), and group(2) captures whatever
# follows the colon on that same line, empty string when the heading is bare.
SECTION_HEAD_RE = re.compile(
    r"^\s*\**\s*(All clear|Needs your attention|Watching)\s*:\s*\**\s*(.*)$", re.IGNORECASE)
_SECTION_KEY_MAP = {"all clear": "all_clear", "needs your attention": "needs_attention",
                     "watching": "watching"}

MD_H1_RE = re.compile(r"^#\s+(.*)$")
MD_H2_RE = re.compile(r"^##\s+(.*)$")
CHECKBOX_ITEM_RE = re.compile(r"^\s*-\s*\[.\]\s*(.*)$")
DETAILS_TAIL_RE = re.compile(r"\s*\*\(details:.*?\)\*\s*$")
ALL_CLEAR_INBOX_LINE = "Nothing is waiting on you. All clear."


# --------------------------------------------------------------------------- subprocess sensors
# Same interpreter re-use pattern as deploy/desk-metrics.py's _run_json_script -- sys.executable
# is already a working Python, so no PATH-based py/python/python3 search is needed.

def _run_json_script(script_path, extra_args):
    if not os.path.isfile(script_path):
        return None, "%s not found" % os.path.basename(script_path)
    cmd = [sys.executable, script_path, "--json"] + list(extra_args)
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
    except Exception as e:  # noqa: BLE001 -- degrade, never crash
        return None, "%s failed to run: %s" % (os.path.basename(script_path), e)
    out = (proc.stdout or "").strip()
    if not out:
        return None, "%s produced no output (exit %s)" % (os.path.basename(script_path), proc.returncode)
    try:
        return json.loads(out), None
    except ValueError:
        return None, "%s output was not valid JSON" % os.path.basename(script_path)


def collect_deadlines_report(deploy_dir, register_path=None, today=None):
    script = os.path.join(deploy_dir, "check-deadlines.py")
    extra = []
    if register_path:
        extra += ["--register", register_path]
    if today:
        extra += ["--today", today]
    data, note = _run_json_script(script, extra)
    if data is None:
        return {"present": False, "note": note}
    if data.get("degraded"):
        return {"present": False, "note": data.get("note", "deadline register absent")}
    return {"present": True, "counts": data.get("counts", {}),
            "rows": data.get("rows", [])}


def collect_trends_report(deploy_dir, history_path):
    script = os.path.join(deploy_dir, "desk-metrics.py")
    extra = ["--trends"]
    if history_path:
        extra += ["--history", history_path]
    data, note = _run_json_script(script, extra)
    if data is None:
        return {"present": False, "note": note}
    return {"present": True, "trends": data.get("trends", []), "note": data.get("note"),
             "load_notes": data.get("load_notes", [])}


# --------------------------------------------------------------------------- SWEEP-BRIEFING.md

def parse_briefing(text):
    """Returns {'all_clear': str|None, 'needs_attention': str|None, 'watching': str|None},
    each the VERBATIM body text of that named section (leading heading line stripped),
    or None if that heading wasn't found at all. A briefing missing every recognized
    heading still returns all-None -- rendered by the caller as its own degrade note,
    never a crash."""
    lines = text.splitlines()
    sections = {"all_clear": None, "needs_attention": None, "watching": None}
    current = None
    buf = []

    def flush():
        if current is not None:
            body = "\n".join(buf).strip("\n")
            sections[current] = body

    for raw in lines:
        m = SECTION_HEAD_RE.match(raw.strip())
        key = _SECTION_KEY_MAP.get(m.group(1).lower()) if m else None
        if key:
            flush()
            current = key
            rest = m.group(2).strip()
            buf = [rest] if rest else []
            continue
        if current is not None:
            buf.append(raw)
    flush()
    return sections


def render_prose(text):
    """Escape-and-paragraph a block of verbatim markdown-ish text: blank-line-separated
    paragraphs, single newlines become <br>. Deliberately minimal -- the design intent is
    VERBATIM content, not a markdown renderer."""
    if not text or not text.strip():
        return "<p class=\"muted\">(empty)</p>"
    paras = re.split(r"\n\s*\n", text.strip())
    out = []
    for p in paras:
        escaped = _html.escape(p).replace("\n", "<br>")
        out.append("<p>%s</p>" % escaped)
    return "\n".join(out)


# --------------------------------------------------------------------------- DECISIONS-PENDING.md

def parse_decisions(text):
    """Returns (all_clear_bool, [{'heading': str, 'items': [str, ...]}, ...]). Item text
    has its trailing '*(details: ...)*' tail stripped (the path already lives in the
    heading grouping / the source file, not needed twice on a static page) and is
    otherwise verbatim."""
    lines = text.splitlines()
    if ALL_CLEAR_INBOX_LINE in text:
        return True, []
    groups = []
    current = None
    for raw in lines:
        m = MD_H2_RE.match(raw.strip())
        if m:
            current = {"heading": m.group(1).strip(), "items": []}
            groups.append(current)
            continue
        m = CHECKBOX_ITEM_RE.match(raw)
        if m and current is not None:
            item_text = DETAILS_TAIL_RE.sub("", m.group(1)).strip()
            current["items"].append(item_text)
    groups = [g for g in groups if g["items"]]
    return False, groups


def load_inbox_first_seen(path):
    """Best-effort reader for deploy/decision-inbox.py's sidecar. Recognizes two
    reasonable shapes and degrades to {} (no ages available) for anything else -- this
    script does not own that sidecar's schema, so it never trusts it further than a
    simple item-text -> date-string lookup permits."""
    if not path or not os.path.isfile(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return {}
    result = {}
    if isinstance(data, dict):
        for k, v in data.items():
            if isinstance(k, str) and isinstance(v, str):
                result[k] = v
            elif isinstance(k, str) and isinstance(v, dict):
                fs = v.get("first_seen") or v.get("date")
                if isinstance(fs, str):
                    result[k] = fs
    elif isinstance(data, list):
        for entry in data:
            if isinstance(entry, dict):
                item = entry.get("item") or entry.get("key") or entry.get("text")
                fs = entry.get("first_seen") or entry.get("date")
                if isinstance(item, str) and isinstance(fs, str):
                    result[item] = fs
    return result


def age_days(first_seen_str, today):
    try:
        d = datetime.strptime(first_seen_str[:10], "%Y-%m-%d").date()
    except ValueError:
        return None
    return (today - d).days


# --------------------------------------------------------------------------- render: HTML

_PAGE_TMPL = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>The Desk</title>
<style>
%(css)s
</style>
</head>
<body>
<header class="hero">
  <div class="hero-inner">
    <span class="stamp-badge">generated %(generated_at)s</span>
    <h1>The Desk</h1>
    <p class="promise">A static, read-only projection of what's already true on disk --
    no button here does anything; every link only opens a file. Regenerated by the
    write-side scheduled session, right after it appends today's metrics line.</p>
    <div class="reflinks">%(reflinks)s</div>
  </div>
</header>
<main>
%(sections)s
</main>
<footer>
  This page performs no actions. It is regenerated by <code>deploy/gen-desk.py</code>
  from SWEEP-BRIEFING.md, DECISIONS-PENDING.md, the deadline register, and the metrics
  history -- never hand-edit it, the sources win.
</footer>
</body>
</html>
"""

_CSS = """
:root{
  --bg:#f6f7fb; --surface:#ffffff; --surface-2:#eef0f7; --border:#e2e5ef; --border-strong:#c9cede;
  --text:#191c26; --text-dim:#525a6e; --text-faint:#8a90a3;
  --accent:#5057d6; --accent-2:#8a5bd6; --accent-ink:#3f46c4;
  --accent-ring:rgba(80,87,214,.18); --accent-tint:rgba(80,87,214,.07);
  --ok:#0d7a58; --ok-bg:#e2f3ec;
  --warm:#9a6410; --warm-strong:#b5761a; --warm-bg:#faf0dc; --warm-ring:rgba(181,118,26,.22);
  --bad:#b0392f; --bad-bg:#fbe6e3; --bad-ring:rgba(176,57,47,.22);
  --shadow-1:0 1px 2px rgba(22,26,45,.05), 0 4px 14px rgba(22,26,45,.06);
  --mono:"SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace;
  --sans:-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  color-scheme: light dark;
}
@media (prefers-color-scheme: dark){
  :root{
    --bg:#0c0f16; --surface:#141926; --surface-2:#1b2233; --border:#242c40; --border-strong:#39435e;
    --text:#e9ebf3; --text-dim:#a6adc2; --text-faint:#6d7488;
    --accent:#8d94ff; --accent-2:#bd93f5; --accent-ink:#a6abff;
    --accent-ring:rgba(141,148,255,.22); --accent-tint:rgba(141,148,255,.09);
    --ok:#4fd6a5; --ok-bg:#12332a;
    --warm:#e8b464; --warm-strong:#f0bf72; --warm-bg:#332711; --warm-ring:rgba(232,180,100,.24);
    --bad:#e8867a; --bad-bg:#3a1c18; --bad-ring:rgba(232,134,122,.28);
    --shadow-1:0 1px 2px rgba(0,0,0,.35), 0 6px 18px rgba(0,0,0,.30);
  }
}
:root[data-theme="dark"]{
  --bg:#0c0f16; --surface:#141926; --surface-2:#1b2233; --border:#242c40; --border-strong:#39435e;
  --text:#e9ebf3; --text-dim:#a6adc2; --text-faint:#6d7488;
  --accent:#8d94ff; --accent-2:#bd93f5; --accent-ink:#a6abff;
  --accent-ring:rgba(141,148,255,.22); --accent-tint:rgba(141,148,255,.09);
  --ok:#4fd6a5; --ok-bg:#12332a;
  --warm:#e8b464; --warm-strong:#f0bf72; --warm-bg:#332711; --warm-ring:rgba(232,180,100,.24);
  --bad:#e8867a; --bad-bg:#3a1c18; --bad-ring:rgba(232,134,122,.28);
  --shadow-1:0 1px 2px rgba(0,0,0,.35), 0 6px 18px rgba(0,0,0,.30);
}
:root[data-theme="light"]{
  --bg:#f6f7fb; --surface:#ffffff; --surface-2:#eef0f7; --border:#e2e5ef; --border-strong:#c9cede;
  --text:#191c26; --text-dim:#525a6e; --text-faint:#8a90a3;
  --accent:#5057d6; --accent-2:#8a5bd6; --accent-ink:#3f46c4;
  --accent-ring:rgba(80,87,214,.18); --accent-tint:rgba(80,87,214,.07);
  --ok:#0d7a58; --ok-bg:#e2f3ec;
  --warm:#9a6410; --warm-strong:#b5761a; --warm-bg:#faf0dc; --warm-ring:rgba(181,118,26,.22);
  --bad:#b0392f; --bad-bg:#fbe6e3; --bad-ring:rgba(176,57,47,.22);
  --shadow-1:0 1px 2px rgba(22,26,45,.05), 0 4px 14px rgba(22,26,45,.06);
}
*{box-sizing:border-box;}
html,body{margin:0; padding:0;}
body{background:var(--bg); color:var(--text); font-family:var(--sans); font-size:15.5px; line-height:1.6; padding:0 0 48px 0;}
code{font-family:var(--mono); font-size:0.84em; background:var(--surface-2); border:1px solid var(--border);
     border-radius:5px; padding:1.5px 6px; color:var(--text);}
a{color:var(--accent-ink);}
.hero{border-bottom:1px solid var(--border); background:var(--surface);}
.hero-inner{max-width:980px; margin:0 auto; padding:30px 28px 20px 28px;}
.stamp-badge{font-family:var(--mono); font-size:0.74rem; color:var(--accent-ink); background:var(--accent-tint);
             border:1px solid var(--accent-ring); border-radius:999px; padding:5px 13px; display:inline-block;}
.hero h1{margin:12px 0 8px 0; font-size:2.1rem; letter-spacing:-0.02em; font-weight:800;}
.hero .promise{margin:0 0 14px 0; color:var(--text-dim); max-width:760px;}
.reflinks{display:flex; flex-wrap:wrap; gap:8px 18px; font-size:0.86rem;}
main{max-width:980px; margin:0 auto; padding:26px 28px 10px 28px;}
section.card-section{margin-bottom:28px;}
h2.section-title{margin:0 0 10px 0; font-size:1.25rem; letter-spacing:-0.01em; font-weight:750;}
.card{background:var(--surface); border:1px solid var(--border); border-radius:14px;
      padding:16px 20px; box-shadow:var(--shadow-1); margin-bottom:12px;}
.card.warm{border-color:var(--warm-ring); box-shadow:var(--shadow-1), 0 0 0 1px var(--warm-ring);}
.card.bad{border-color:var(--bad-ring); box-shadow:var(--shadow-1), 0 0 0 1px var(--bad-ring);}
.card h3{margin:0 0 8px 0; font-size:1.0rem;}
.muted{color:var(--text-faint);}
.badge{font-size:0.66rem; text-transform:uppercase; letter-spacing:0.05em; padding:3px 9px;
       border-radius:999px; font-weight:800; display:inline-block;}
.badge.ok{background:var(--ok-bg); color:var(--ok);}
.badge.warm{background:var(--warm-bg); color:var(--warm);}
.badge.bad{background:var(--bad-bg); color:var(--bad);}
.item-list{list-style:none; margin:0; padding:0;}
.item-list li{padding:8px 0; border-top:1px solid var(--border);}
.item-list li:first-child{border-top:none;}
.age-badge{font-family:var(--mono); font-size:0.72rem; color:var(--text-faint); margin-left:8px;}
.trend-list{margin:0; padding-left:1.2em;}
.notavailable{color:var(--text-faint); font-style:italic;}
footer{max-width:980px; margin:30px auto 0 auto; padding:16px 28px 0 28px; border-top:1px solid var(--border);
       color:var(--text-dim); font-size:0.8rem;}
"""


def _e(s):
    return _html.escape(str(s))


def render_not_available(what):
    return "<p class=\"notavailable\">Not available -- %s.</p>" % _e(what)


def render_briefing_section(briefing_present, sections, note):
    parts = ["<section class=\"card-section\"><h2 class=\"section-title\">From the last sweep</h2>"]
    if not briefing_present:
        parts.append("<div class=\"card\">%s</div>" % render_not_available(note or "SWEEP-BRIEFING.md not found"))
        parts.append("</section>")
        return "\n".join(parts)

    def block(title, key, css):
        body = sections.get(key)
        if body is None:
            inner = render_not_available("no '%s' heading found in SWEEP-BRIEFING.md" % title)
        else:
            inner = render_prose(body)
        return "<div class=\"card %s\"><h3>%s</h3>%s</div>" % (css, _e(title), inner)

    parts.append(block("All clear", "all_clear", ""))
    parts.append(block("Needs your attention", "needs_attention", "warm"))
    parts.append(block("Watching", "watching", ""))
    parts.append("</section>")
    return "\n".join(parts)


def render_decisions_section(decisions_present, all_clear, groups, first_seen, today, note):
    parts = ["<section class=\"card-section\"><h2 class=\"section-title\">Waiting on you</h2>"]
    if not decisions_present:
        parts.append("<div class=\"card\">%s</div>" % render_not_available(note or "DECISIONS-PENDING.md not found"))
        parts.append("</section>")
        return "\n".join(parts)
    if all_clear:
        parts.append("<div class=\"card\"><span class=\"badge ok\">clear</span> "
                      "<p style=\"display:inline\"> Nothing is waiting on you.</p></div>")
        parts.append("</section>")
        return "\n".join(parts)
    for g in groups:
        parts.append("<div class=\"card\"><h3>%s</h3><ul class=\"item-list\">" % _e(g["heading"]))
        for item in g["items"]:
            age_html = ""
            fs = first_seen.get(item)
            if fs:
                d = age_days(fs, today)
                if d is not None:
                    age_html = "<span class=\"age-badge\">waiting %d day%s (since %s)</span>" % (
                        d, "" if d == 1 else "s", _e(fs[:10]))
            parts.append("<li>%s%s</li>" % (_e(item), age_html))
        parts.append("</ul></div>")
    parts.append("</section>")
    return "\n".join(parts)


_CAT_LABELS = (
    ("attention", "Attention -- due within 30 days", "warm"),
    ("fired", "Fired -- overdue", "bad"),
    ("watching", "Watching (dated, not yet due)", ""),
    ("if-row", "Watching-conditions", ""),
)


def render_deadlines_section(report):
    parts = ["<section class=\"card-section\"><h2 class=\"section-title\">Deadline countdowns</h2>"]
    if not report.get("present"):
        parts.append("<div class=\"card\">%s</div>" % render_not_available(
            report.get("note") or "deadline register not available"))
        parts.append("</section>")
        return "\n".join(parts)
    rows = report.get("rows", [])
    by_cat = {}
    for r in rows:
        by_cat.setdefault(r.get("category"), []).append(r)
    for cat, label, css in _CAT_LABELS:
        items = by_cat.get(cat, [])
        parts.append("<div class=\"card %s\"><h3>%s (%d)</h3>" % (css, _e(label), len(items)))
        if items:
            parts.append("<ul class=\"item-list\">")
            for r in items:
                if cat == "if-row":
                    detail = "if: %s" % r.get("if")
                else:
                    days = r.get("days_remaining")
                    detail = ("%d day(s) remaining, due %s" % (days, r.get("when"))
                               if isinstance(days, int) and days >= 0
                               else "overdue by %d day(s), was due %s" % (-days, r.get("when")))
                parts.append("<li>%s <span class=\"muted\">-- %s</span></li>" % (_e(r.get("what")), _e(detail)))
            parts.append("</ul>")
        else:
            parts.append("<p class=\"muted\">(none)</p>")
        parts.append("</div>")
    parts.append("</section>")
    return "\n".join(parts)


def render_trends_section(report):
    parts = ["<section class=\"card-section\"><h2 class=\"section-title\">Metrics trends</h2>"]
    if not report.get("present"):
        parts.append("<div class=\"card\">%s</div>" % render_not_available(
            report.get("note") or "desk-metrics.py not available"))
        parts.append("</section>")
        return "\n".join(parts)
    trends = report.get("trends") or []
    if trends:
        parts.append("<div class=\"card\"><ul class=\"trend-list\">")
        for t in trends:
            parts.append("<li>%s</li>" % _e(t))
        parts.append("</ul></div>")
    else:
        parts.append("<div class=\"card\">%s</div>" % render_not_available(
            report.get("note") or "no trend lines yet"))
    parts.append("</section>")
    return "\n".join(parts)


def render_reflinks(root, briefing_path, decisions_path, register_path):
    links = []
    for label, path in (("SWEEP-BRIEFING.md", briefing_path),
                         ("DECISIONS-PENDING.md", decisions_path),
                         ("deadline-register.yaml", register_path)):
        if path and os.path.isfile(path):
            rel = os.path.relpath(path, root).replace("\\", "/")
            links.append("<a href=\"%s\">%s</a>" % (_e(rel), _e(label)))
    if not links:
        return "<span class=\"muted\">(no source files found to link)</span>"
    return " &middot; ".join(links)


def render_page(root, briefing_path, decisions_path, inbox_first_seen_path,
                 deadlines_report, trends_report, register_path, today):
    briefing_text = None
    if briefing_path and os.path.isfile(briefing_path):
        with open(briefing_path, "r", encoding="utf-8-sig", errors="replace") as fh:
            briefing_text = fh.read()
    briefing_sections = parse_briefing(briefing_text) if briefing_text is not None else {}
    briefing_note = None if briefing_text is not None else "SWEEP-BRIEFING.md not found"

    decisions_text = None
    if decisions_path and os.path.isfile(decisions_path):
        with open(decisions_path, "r", encoding="utf-8-sig", errors="replace") as fh:
            decisions_text = fh.read()
    if decisions_text is not None:
        all_clear, groups = parse_decisions(decisions_text)
        decisions_note = None
    else:
        all_clear, groups = False, []
        decisions_note = "DECISIONS-PENDING.md not found"

    first_seen = load_inbox_first_seen(inbox_first_seen_path)

    sections_html = "\n".join([
        render_briefing_section(briefing_text is not None, briefing_sections, briefing_note),
        render_decisions_section(decisions_text is not None, all_clear, groups, first_seen, today, decisions_note),
        render_deadlines_section(deadlines_report),
        render_trends_section(trends_report),
    ])

    reflinks = render_reflinks(root, briefing_path, decisions_path, register_path)

    return _PAGE_TMPL % {
        "css": _CSS,
        "generated_at": _e(today.isoformat()),
        "reflinks": reflinks,
        "sections": sections_html,
    }


# --------------------------------------------------------------------------- CLI

def _arg_value(args, flag):
    if flag in args:
        i = args.index(flag)
        if i + 1 < len(args):
            return args[i + 1]
    return None


def generate(root, out_path=None, briefing_path=None, decisions_path=None,
             inbox_first_seen_path=None, deploy_dir=None, history_path=None,
             register_path=None, fork_root=None, template_root=None, today=None):
    today = today or date.today()
    deploy_dir = deploy_dir or os.path.join(root, "deploy")
    briefing_path = briefing_path or os.path.join(root, "SWEEP-BRIEFING.md")
    decisions_path = decisions_path or os.path.join(root, "DECISIONS-PENDING.md")
    inbox_first_seen_path = inbox_first_seen_path or os.path.join(
        root, "receipts", "desk", "inbox-first-seen.json")
    history_path = history_path or os.path.join(root, "receipts", "desk", "metrics-history.jsonl")
    out_path = out_path or os.path.join(root, "DESK.html")

    deadlines_report = collect_deadlines_report(deploy_dir, register_path=register_path,
                                                 today=today.isoformat())
    trends_report = collect_trends_report(deploy_dir, history_path)

    # Reflinks display purposes only: check-deadlines.py resolves its OWN default register
    # path (deploy/deadline-register.yaml next to itself) when register_path is None -- this
    # mirrors that same default here just so the link can point at the real file, without
    # changing what gets passed to the subprocess above.
    display_register_path = register_path or os.path.join(deploy_dir, "deadline-register.yaml")

    html_text = render_page(root, briefing_path, decisions_path, inbox_first_seen_path,
                             deadlines_report, trends_report, display_register_path, today)

    d = os.path.dirname(out_path)
    if d and not os.path.isdir(d):
        os.makedirs(d, exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(html_text)
    return out_path, html_text


def main(argv):
    args = argv[1:] if argv and argv[0].endswith(".py") else list(argv)
    if "--self-test" in args:
        return self_test()

    root = _arg_value(args, "--root") or "."
    today = None
    today_s = _arg_value(args, "--today")
    if today_s:
        try:
            today = datetime.strptime(today_s, "%Y-%m-%d").date()
        except ValueError:
            print("gen-desk: NOTE -- unparseable --today value %r, using wall-clock date" % today_s)

    out_path, _text = generate(
        root,
        out_path=_arg_value(args, "--out"),
        briefing_path=_arg_value(args, "--briefing"),
        decisions_path=_arg_value(args, "--decisions"),
        inbox_first_seen_path=_arg_value(args, "--inbox-first-seen"),
        deploy_dir=_arg_value(args, "--deploy-dir"),
        history_path=_arg_value(args, "--history"),
        register_path=_arg_value(args, "--register"),
        fork_root=_arg_value(args, "--fork-root"),
        template_root=_arg_value(args, "--template-root"),
        today=today,
    )
    print("gen-desk: wrote %s" % out_path)
    return 0


# --------------------------------------------------------------------------- self-test

def self_test():
    import shutil
    import tempfile

    total = failed = 0

    def case(name, ok, detail=""):
        nonlocal total, failed
        total += 1
        status = "ok " if ok else "XX "
        print("  %s %s%s" % (status, name, ("  << " + repr(detail)) if (not ok and detail != "") else ""))
        if not ok:
            failed += 1

    NOW = date(2026, 7, 23)

    def write(path, text):
        d = os.path.dirname(path)
        if d:
            os.makedirs(d, exist_ok=True)
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)

    # ---- parse_briefing -------------------------------------------------------------
    fixture_briefing = (
        "<!-- generated -->\n\n# Sweep briefing\n\n"
        "**All clear:** 3 checks ran clean, no findings.\n\n"
        "**Needs your attention:**\n\n"
        "1. First finding sentence one. Sentence two. Sentence three.\n"
        "   (details: some/path.md)\n"
        "2. Second finding.\n\n"
        "**Watching:**\n"
        "- A declared red, expected not a problem.\n"
    )
    parsed = parse_briefing(fixture_briefing)
    case("parse_briefing: all_clear captured", "3 checks ran clean" in (parsed["all_clear"] or ""), parsed)
    case("parse_briefing: needs_attention captured, both items present",
         "First finding" in (parsed["needs_attention"] or "") and "Second finding" in (parsed["needs_attention"] or ""),
         parsed)
    case("parse_briefing: watching captured", "declared red" in (parsed["watching"] or ""), parsed)

    empty_parsed = parse_briefing("just some prose, no recognized headings at all\n")
    case("parse_briefing: no recognized headings -> all three None",
         all(v is None for v in empty_parsed.values()), empty_parsed)

    # ---- render_prose escaping --------------------------------------------------------
    prose = render_prose("line one <script>evil()</script>\n\nsecond paragraph")
    case("render_prose: HTML-escapes angle brackets", "<script>" not in prose and "&lt;script&gt;" in prose, prose)
    case("render_prose: empty text -> a muted placeholder, not a crash",
         "(empty)" in render_prose("   \n  "))

    # ---- parse_decisions ---------------------------------------------------------------
    fixture_decisions = (
        "<!-- header -->\n\n# Waiting on you\n\n"
        "## Backlog items awaiting a decision\n"
        "- [ ] Backlog v3.0-21: some title *(details: harness-backlog.md)*\n\n"
        "## From the last sweep\n"
        "- [ ] Sweep finding: something happened (sweep dated 2026-07-23) *(details: SWEEP-BRIEFING.md)*\n"
    )
    all_clear, groups = parse_decisions(fixture_decisions)
    case("parse_decisions: not all-clear", all_clear is False)
    case("parse_decisions: 2 groups parsed", len(groups) == 2, groups)
    case("parse_decisions: details tail stripped from item text",
         all("*(details:" not in it for g in groups for it in g["items"]), groups)

    all_clear2, groups2 = parse_decisions(
        "<!-- header -->\n\n# Waiting on you\n\nNothing is waiting on you. All clear.\n")
    case("parse_decisions: all-clear file recognized", all_clear2 is True and groups2 == [], (all_clear2, groups2))

    # ---- load_inbox_first_seen: tolerant shapes ----------------------------------------
    base = tempfile.mkdtemp(prefix="gen-desk-selftest-")
    try:
        dict_shape = os.path.join(base, "fs-dict.json")
        write(dict_shape, json.dumps({"Backlog v3.0-21: some title": "2026-07-01"}))
        fs1 = load_inbox_first_seen(dict_shape)
        case("load_inbox_first_seen: flat dict shape recognized",
             fs1.get("Backlog v3.0-21: some title") == "2026-07-01", fs1)

        list_shape = os.path.join(base, "fs-list.json")
        write(list_shape, json.dumps([{"item": "Sweep finding: something happened (sweep dated 2026-07-23)",
                                        "first_seen": "2026-07-20"}]))
        fs2 = load_inbox_first_seen(list_shape)
        case("load_inbox_first_seen: list-of-object shape recognized",
             fs2.get("Sweep finding: something happened (sweep dated 2026-07-23)") == "2026-07-20", fs2)

        garbage_shape = os.path.join(base, "fs-garbage.json")
        write(garbage_shape, "not json at all {{{")
        fs3 = load_inbox_first_seen(garbage_shape)
        case("load_inbox_first_seen: malformed JSON degrades to {} not a crash", fs3 == {}, fs3)

        weird_shape = os.path.join(base, "fs-weird.json")
        write(weird_shape, json.dumps({"totally": ["unexpected", "shape"]}))
        fs4 = load_inbox_first_seen(weird_shape)
        case("load_inbox_first_seen: unrecognized shape degrades to {} not a crash", fs4 == {}, fs4)

        fs5 = load_inbox_first_seen(os.path.join(base, "no-such-file.json"))
        case("load_inbox_first_seen: absent file -> {}", fs5 == {})

        case("age_days: computes a positive day count", age_days("2026-07-01", NOW) == 22)
        case("age_days: unparseable string -> None", age_days("not-a-date", NOW) is None)

        # ---- full generate() end-to-end, every source present -----------------------
        root = os.path.join(base, "full-root")
        deploy_dir = os.path.join(root, "deploy")
        os.makedirs(deploy_dir, exist_ok=True)
        for fname in ("check-deadlines.py", "desk-metrics.py"):
            src = os.path.join(_HERE, fname)
            if os.path.isfile(src):
                with open(src, "r", encoding="utf-8") as fh:
                    write(os.path.join(deploy_dir, fname), fh.read())

        write(os.path.join(root, "SWEEP-BRIEFING.md"), fixture_briefing)
        write(os.path.join(root, "DECISIONS-PENDING.md"), fixture_decisions)
        write(os.path.join(root, "receipts", "desk", "inbox-first-seen.json"),
              json.dumps({"Backlog v3.0-21: some title": "2026-07-01"}))
        register_path = os.path.join(root, "deadline-register.yaml")
        write(register_path, "\n".join([
            "rows:",
            "  - what: fixture attention row",
            "    when: 2026-08-01",
            "    source: fixture",
            "    owner: operator",
            "    status: watching",
            "  - what: fixture overdue row",
            "    when: 2026-07-01",
            "    source: fixture",
            "    owner: operator",
            "    status: watching",
        ]))
        history_path = os.path.join(root, "receipts", "desk", "metrics-history.jsonl")
        write(history_path, "\n".join([
            json.dumps({"date": "2026-07-22", "deadlines": {"present": True, "attention": 1}}),
            json.dumps({"date": "2026-07-23", "deadlines": {"present": True, "attention": 2}}),
        ]) + "\n")

        out_path = os.path.join(root, "DESK.html")
        result_path, text = generate(root, out_path=out_path, deploy_dir=deploy_dir,
                                      register_path=register_path, history_path=history_path,
                                      today=NOW)
        case("generate: writes DESK.html at the requested path", os.path.isfile(result_path))
        case("generate: page includes the title", "<title>The Desk</title>" in text)
        case("generate: all four section titles present",
             all(s in text for s in ("From the last sweep", "Waiting on you",
                                      "Deadline countdowns", "Metrics trends")), None)
        case("generate: briefing content rendered verbatim (escaped)",
             "3 checks ran clean" in text and "First finding" in text)
        case("generate: decisions item rendered with an age badge",
             "waiting 22 day" in text or "waiting" in text, text[:0])
        case("generate: deadline countdown row rendered", "fixture attention row" in text, None)
        case("generate: fired (overdue) row rendered", "fixture overdue row" in text, None)
        case("generate: reflinks are relative hrefs, not absolute/file-less",
             'href="SWEEP-BRIEFING.md"' in text and 'href="DECISIONS-PENDING.md"' in text, None)

        # actuator-free invariant: the load-bearing self-test assertion
        lower = text.lower()
        case("ACTUATOR-FREE: zero <script> tags", "<script" not in lower)
        case("ACTUATOR-FREE: zero <form> tags", "<form" not in lower)
        case("ACTUATOR-FREE: zero <button> tags", "<button" not in lower)
        case("ACTUATOR-FREE: no javascript: URIs", "javascript:" not in lower)
        case("ACTUATOR-FREE: no onclick/inline-event handlers", "onclick=" not in lower and "onload=" not in lower)

        # ---- generate() with EVERY source absent -> honest not-available blocks --------
        empty_root = os.path.join(base, "empty-root")
        os.makedirs(empty_root, exist_ok=True)
        out2, text2 = generate(empty_root, today=NOW)
        case("generate (all-absent): still writes a file", os.path.isfile(out2))
        case("generate (all-absent): not-available appears for the briefing",
             "SWEEP-BRIEFING.md not found" in text2, None)
        case("generate (all-absent): not-available appears for decisions",
             "DECISIONS-PENDING.md not found" in text2, None)
        case("generate (all-absent): not-available appears for deadlines/trends",
             "not found" in text2, None)
        lower2 = text2.lower()
        case("ACTUATOR-FREE (all-absent): zero <script>/<form>/<button>",
             "<script" not in lower2 and "<form" not in lower2 and "<button" not in lower2)

        # ---- CLI wiring smoke ------------------------------------------------------------
        rc = main(["--root", root, "--out", os.path.join(root, "DESK2.html"),
                   "--deploy-dir", deploy_dir, "--register", register_path,
                   "--history", history_path, "--today", "2026-07-23"])
        case("CLI: main() returns 0 and writes the requested --out path",
             rc == 0 and os.path.isfile(os.path.join(root, "DESK2.html")))

        rc2 = main(["--root", root, "--out", os.path.join(root, "DESK3.html"), "--today", "bogus-date"])
        case("CLI: an unparseable --today degrades to wall-clock date, still returns 0", rc2 == 0)

    finally:
        shutil.rmtree(base, ignore_errors=True)

    print("gen-desk self-test: %s (%d/%d)"
          % ("PASS" if failed == 0 else "FAIL", total - failed, total))
    return 0 if failed == 0 else 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
