#!/usr/bin/env python3
"""gen-skill-adapters.py -- generated, tracked skill-discovery adapters for non-Claude
agents (backlog v3.0-79; moved into core by v3.0-236).

Codex (and other agents following the .agents convention) discover repository skills from
`.agents/skills/<name>/SKILL.md`; this repo's canonical skill protocols live at
`.claude/skills/<name>/SKILL.md`. The historical answer was a HAND-BUILT mirror -- which
this repo's own review corpus condemned in June 2026 ("untracked mirror harnesses sit
outside every sensor's scope", wiki/REVIEW.md; "mirror ownership unclear", receipts
2026-06-11): hand copies drift silently. This generator replaces the copy with a derived
projection: one pointer adapter per installed skill, frontmatter (name + description)
copied from the canonical skill and YAML-quoted so a strict loader parses it, body a
pointer to the canonical protocol -- never duplicated instructions (single-home rule).
Adapters are TRACKED and regenerable; /doctor's skill-adapters check runs `--check` so
drift fails loud instead of accumulating invisibly.

HOME (v3.0-236): this file ships with the core doctor skill -- core/skills/doctor/ in the
template, .claude/skills/doctor/ in every instantiated project, on both init paths and
with or without knowledge-os. `deploy/gen-skill-adapters.py` (knowledge-os projects) is a
forwarding stub to this file, kept so the doctor's check and existing instructions still
resolve.

SKIPPED skills are listed in `skill-adapter-skip.list` beside this file (data, not code).
The list is empty by design since v3.0-236's routing remainder: the two bridge skills it
used to hide (cross-check, cross-check-loop) now read the session driver and route to the
other vendor, so none is Claude-only. Do not add skills to it -- an adapter makes a skill
discoverable, not Claude-runnable, and hiding skills from a non-Claude driver is the
v3.0-182 mistake.

Usage:
  gen-skill-adapters.py [--root DIR]         regenerate .agents/skills/ (idempotent)
  gen-skill-adapters.py --check [--root DIR] exit 0 if current, 1 if regeneration would
                                             change anything (doctor consumes this)
  gen-skill-adapters.py --parity [--root DIR] exit 0 if every non-skipped canonical skill
                                             has an adapter whose target path exists
  gen-skill-adapters.py --list-skipped       print the skip list, one name per line
  gen-skill-adapters.py --self-test          embedded fixtures, temp dir only
Exit: 0 ok/current | 1 drift (--check), parity gap (--parity) or self-test failure |
      2 usage/environment error.
"""

import argparse
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path

try:  # strict parse of the emitted frontmatter when available; never required
    import yaml as _yaml
except Exception:  # pragma: no cover - PyYAML optional
    _yaml = None

HERE = Path(__file__).resolve().parent
SKIP_LIST_FILE = HERE / "skill-adapter-skip.list"

_FM_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n", re.DOTALL)
_NAME_RE = re.compile(r"(?m)^name:\s*(.+?)\s*$")
_DESC_RE = re.compile(r"(?m)^description:\s*(.+?)\s*$")
_TARGET_RE = re.compile(r"(?m)^\s+(\.claude/skills/[^\s/]+/SKILL\.md)\s*$")

ADAPTER_BODY = """\
# /%(name)s — discovery adapter

**This file is a GENERATED pointer, not the protocol.** The canonical, complete protocol
for this skill lives at:

    .claude/skills/%(name)s/SKILL.md

Read and follow that file; treat this adapter as a signpost only. The `.claude/` path is
a Claude Code layout convention, nothing more — the protocol itself is substrate-neutral
and binds any agent that runs it (see AGENTS.md, "Skills are protocols, not Claude
features").

Do not edit this file and do not add instructions here (single-home rule): it is
regenerated by `python .claude/skills/doctor/gen-skill-adapters.py` (knowledge-os
projects may also call it as `deploy/gen-skill-adapters.py`), and /doctor's
`skill-adapters` check flags any drift between the adapters and the canonical skill set.
"""


def load_skip_list(path=SKIP_LIST_FILE):
    """{skill_name: reason} from the data file beside this script; empty if absent."""
    out = {}
    if not Path(path).is_file():
        return out
    for raw in Path(path).read_text(encoding="utf-8", errors="ignore").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        name, _, reason = line.partition("#")
        name = name.strip()
        if name:
            out[name] = reason.strip()
    return out


def _unquote(value):
    """A canonical frontmatter value that is already quoted ("..." / '...') -> raw text."""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        inner = value[1:-1]
        if value[0] == "'":
            return inner.replace("''", "'")
        try:
            return json.loads(value)
        except ValueError:
            return inner.replace('\\"', '"')
    return value


def yaml_quote(value):
    """A YAML double-quoted scalar: JSON string escaping is a subset of YAML's, so a
    description holding `: `, ` -- `, `#`, quotes or backslashes parses under a strict
    loader and round-trips to the same text."""
    return json.dumps(value, ensure_ascii=False)


def _parse_frontmatter(text):
    """(name, description) from a SKILL.md, or (None, None) if unparseable."""
    m = _FM_RE.match(text)
    if not m:
        return None, None
    block = m.group(1)
    name = _NAME_RE.search(block)
    desc = _DESC_RE.search(block)
    return (_unquote(name.group(1)) if name else None,
            _unquote(desc.group(1)) if desc else None)


def render_adapter(name, description):
    return ("---\n"
            "name: %s\n"
            "description: %s\n"
            "---\n\n" % (yaml_quote(name), yaml_quote(description))) \
        + ADAPTER_BODY % {"name": name}


def desired_adapters(root, skip=None):
    """{skill_name: adapter_text} for every canonical skill not skipped."""
    skip = load_skip_list() if skip is None else skip
    skills_dir = root / ".claude" / "skills"
    out = {}
    if not skills_dir.is_dir():
        return out
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        skill = skill_md.parent.name
        if skill in skip:
            continue
        name, desc = _parse_frontmatter(skill_md.read_text(encoding="utf-8",
                                                            errors="ignore"))
        if not name or not desc:
            print("WARN: %s has no parseable name/description frontmatter -- skipped "
                  "(fix the canonical skill, then re-run)" % skill_md, file=sys.stderr)
            continue
        out[skill] = render_adapter(name, desc)
    return out


def current_adapters(root):
    """{skill_name: adapter_text} for what is on disk under .agents/skills/."""
    agents_dir = root / ".agents" / "skills"
    out = {}
    if not agents_dir.is_dir():
        return out
    for adapter_md in sorted(agents_dir.glob("*/SKILL.md")):
        out[adapter_md.parent.name] = adapter_md.read_text(encoding="utf-8",
                                                            errors="ignore")
    return out


def diff(root, skip=None):
    """(stale, missing, orphaned) skill-name lists. Empty everywhere == current."""
    want = desired_adapters(root, skip)
    have = current_adapters(root)
    stale = sorted(k for k in want if k in have and have[k] != want[k])
    missing = sorted(k for k in want if k not in have)
    orphaned = sorted(k for k in have if k not in want)
    return stale, missing, orphaned


def parity(root, skip=None):
    """Problems as strings: every non-skipped .claude/skills/<name>/SKILL.md must have an
    .agents/skills/<name>/SKILL.md adapter whose pointed-at target path exists. This is
    the check both init validators run natively; kept here for the self-test and for a
    one-command local run."""
    skip = load_skip_list() if skip is None else skip
    problems = []
    skills_dir = root / ".claude" / "skills"
    if not skills_dir.is_dir():
        return problems
    for skill_md in sorted(skills_dir.glob("*/SKILL.md")):
        skill = skill_md.parent.name
        if skill in skip:
            continue
        adapter = root / ".agents" / "skills" / skill / "SKILL.md"
        if not adapter.is_file():
            problems.append("missing adapter: .agents/skills/%s/SKILL.md" % skill)
            continue
        m = _TARGET_RE.search(adapter.read_text(encoding="utf-8", errors="ignore"))
        if not m:
            problems.append("adapter names no target: .agents/skills/%s/SKILL.md" % skill)
        elif not (root / m.group(1)).is_file():
            problems.append("adapter target missing: .agents/skills/%s -> %s"
                            % (skill, m.group(1)))
    return problems


def regenerate(root, skip=None):
    skip = load_skip_list() if skip is None else skip
    want = desired_adapters(root, skip)
    agents_dir = root / ".agents" / "skills"
    _, missing, orphaned = diff(root, skip)
    for skill, text in want.items():
        d = agents_dir / skill
        d.mkdir(parents=True, exist_ok=True)
        target = d / "SKILL.md"
        if not target.exists() or target.read_text(encoding="utf-8",
                                                    errors="ignore") != text:
            target.write_text(text, encoding="utf-8", newline="\n")
    for skill in orphaned:
        shutil.rmtree(agents_dir / skill)
    return len(want), len(missing), len(orphaned)


def self_test():
    failed = total = 0

    def check(label, cond):
        nonlocal failed, total
        total += 1
        print("  %s %s" % ("ok " if cond else "XX ", label))
        if not cond:
            failed += 1

    skip = {"cross-check": "fixture skip"}
    tricky = ('Contract: convergence check -- then "lock" it; also --round N '
              '(a #comment-looking tail) \\ backslash')

    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        sk = root / ".claude" / "skills"
        for name, desc in (("alpha", "First test skill."),
                            ("cross-check", "Skipped by design."),
                            ("beta", "Second test skill."),
                            ("gamma", tricky)):
            d = sk / name
            d.mkdir(parents=True)
            (d / "SKILL.md").write_text("---\nname: %s\ndescription: %s\n---\nbody\n"
                                         % (name, desc), encoding="utf-8")

        n, missing, orphaned = regenerate(root, skip)
        check("generates one adapter per non-skipped skill (3, not 4)", n == 3)
        check("skip-listed skill got no adapter",
              not (root / ".agents" / "skills" / "cross-check").exists())
        alpha = (root / ".agents" / "skills" / "alpha" / "SKILL.md").read_text(
            encoding="utf-8")
        check("adapter carries copied description", "First test skill." in alpha)
        check("adapter frontmatter is quoted",
              'name: "alpha"\ndescription: "First test skill."\n' in alpha)
        s, m, o = diff(root, skip)
        check("post-regenerate: current (no stale/missing/orphaned)",
              not s and not m and not o)
        check("post-regenerate: parity holds", parity(root, skip) == [])

        # Quoting: a description with `: `, ` -- `, quotes, `#` and a backslash must
        # parse under a strict YAML loader and round-trip to the same text.
        gamma = (root / ".agents" / "skills" / "gamma" / "SKILL.md").read_text(
            encoding="utf-8")
        fm = _FM_RE.match(gamma).group(1)
        if _yaml is not None:
            try:
                loaded = _yaml.safe_load(fm)
            except Exception:
                loaded = None
            check("PyYAML: tricky description parses strictly and round-trips",
                  isinstance(loaded, dict) and loaded.get("description") == tricky
                  and loaded.get("name") == "gamma")
        else:
            check("(no PyYAML) tricky description is a double-quoted scalar",
                  fm.splitlines()[1].startswith('description: "')
                  and fm.splitlines()[1].endswith('"'))
        check("quoted-in-canonical frontmatter is not double-wrapped",
              _parse_frontmatter('---\nname: "q"\ndescription: "a: b"\n---\n')
              == ("q", "a: b"))

        # Skip-list data file: parsed with comments and inline reasons.
        lst = root / "skip.list"
        lst.write_text("# header\n\ncross-check  # reason one\ncross-check-loop\n",
                       encoding="utf-8")
        check("skip list file parses (names, comments, inline reasons)",
              load_skip_list(lst) == {"cross-check": "reason one",
                                      "cross-check-loop": ""})

        # Parity: a deleted adapter and a dangling target are both reported.
        shutil.rmtree(root / ".agents" / "skills" / "beta")
        check("parity: missing adapter reported",
              parity(root, skip) == ["missing adapter: .agents/skills/beta/SKILL.md"])
        regenerate(root, skip)
        (root / ".agents" / "skills" / "beta" / "SKILL.md").write_text(
            "---\nname: \"beta\"\ndescription: \"x\"\n---\n\n    .claude/skills/nope/SKILL.md\n",
            encoding="utf-8")
        check("parity: dangling target reported",
              parity(root, skip) == ["adapter target missing: .agents/skills/beta -> "
                                     ".claude/skills/nope/SKILL.md"])
        regenerate(root, skip)

        # Drift: canonical description changes -> adapter stale until regenerated.
        (sk / "alpha" / "SKILL.md").write_text(
            "---\nname: alpha\ndescription: CHANGED.\n---\nbody\n", encoding="utf-8")
        s, m, o = diff(root, skip)
        check("canonical edit -> adapter reported stale", s == ["alpha"])

        # Orphan: skill deleted -> adapter reported orphaned, removed on regenerate.
        shutil.rmtree(sk / "beta")
        s, m, o = diff(root, skip)
        check("deleted skill -> adapter reported orphaned", o == ["beta"])
        regenerate(root, skip)
        s, m, o = diff(root, skip)
        check("regenerate heals stale + removes orphan", not s and not m and not o)

    print("gen-skill-adapters self-test: %s (%d/%d)"
          % ("FAIL" if failed else "PASS", total - failed, total))
    return 1 if failed else 0


def main(argv=None):
    ap = argparse.ArgumentParser(prog="gen-skill-adapters.py")
    ap.add_argument("--root", default=None)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--parity", action="store_true")
    ap.add_argument("--list-skipped", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    args = ap.parse_args(argv)
    if args.self_test:
        return self_test()
    skip = load_skip_list()
    if args.list_skipped:
        for name in sorted(skip):
            print(name)
        return 0
    root = Path(args.root).resolve() if args.root else Path.cwd().resolve()
    if not (root / ".claude" / "skills").is_dir():
        print("gen-skill-adapters: no .claude/skills under %s" % root, file=sys.stderr)
        return 2
    if args.parity:
        problems = parity(root, skip)
        for p in problems:
            print("skill-adapters PARITY: " + p)
        if problems:
            return 1
        print("skill-adapters parity ok (%d skills skipped by the list)" % len(skip))
        return 0
    if args.check:
        stale, missing, orphaned = diff(root, skip)
        if stale or missing or orphaned:
            print("skill-adapters DRIFT: stale=%s missing=%s orphaned=%s"
                  % (stale, missing, orphaned))
            return 1
        print("skill-adapters current (%d adapters, %d skills skipped by the list)"
              % (len(desired_adapters(root, skip)), len(skip)))
        return 0
    n, missing, orphaned = regenerate(root, skip)
    print("skill-adapters regenerated: %d adapter(s); %d were missing, %d orphan(s) "
          "removed; skipped by the list: %s"
          % (n, missing, orphaned, ", ".join(sorted(skip)) or "(none)"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
